
name: dishcovery
description: Dishcovery - simple recipe finder MVP
publish_to: 'none'

version: 3.0.0+4

environment:
  sdk: '^3.10.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  shared_preferences: ^2.2.0
  flutter_riverpod: ^2.3.6
  cached_network_image: ^3.2.3
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "icons/dishcovery_logo.png"
  android: true
  ios: true
  

flutter:
  uses-material-design: true
  assets:
    - lib/data/recipes.json

